### ISSUE TITLE
Knife models and new cs:go update

### ISSUE THREAD

**Issue by notradger** [aixxe/Chameleon#3]
The new update broke the knife models again hehe.. 

Can I ask you what offset dumper you use to obtain the values needed in iClientEntity.h ??

**Comment by aixxe** [comment]
Fixed. As for the offsets, I use my own but any that dump NetVars work just fine.

**Comment by notradger** [comment]
Because the one I use spews out too much information.... and like.. I cant quite figure out some of the netvars.. and how they relate to the iClientEntity.h file.. 

For example(iClientEntry.h): #define m_iItemDefinitionIndex     0x1D8
CSGO Dumper(NetvarManager.txt):   |**m_iItemDefinitionIndex________________________** -> 0x2F88 ( int )

Mismatch on that particular one..  Im confused.. lol

Is your offset dumper public?

**Comment by aixxe** [comment]
The offset dumper from Y3t1y3t adds up parent offsets. Since the `m_iItemDefinitionIndex` offset is added from `m_Item` and `m_AttributeManager` you get that combined offset.

You're free to change the lines in `IClientEntity.h` to use the combined offset like so:

```
inline int* GetItemDefinitionIndex() {
    return (int*)((DWORD)this + 0x2F88);
}
```

I don't have an offset dumper per se, I just have a class in my personal projects that can iterate the client data tables recursively and get the offsets dynamically. It's nothing new but this is a simple project so it's been purposely excluded. [One such example can be found in MarkHC's internal base.](https://github.com/MarkHC/CSGOSimple/blob/master/CSGOSimple/NetvarManager.cpp)
