### ISSUE TITLE
Crashes CSGO

### ISSUE THREAD

**Issue by notradger** [aixxe/Chameleon#8]
Well.. Hehe.. I guess all those heavy updates screwed it up again.. I'm using the netvar manager from that one package you referred me to before so i don't think its the offsets..  

I'm at a loss to what it could be..

**Comment by aixxe** [comment]
Just compiled from source and it works just fine for me. Make sure you've pulled the latest updates, otherwise it's likely an issue with any changes you've made to the code.

Also, check out [chameleon-ng](https://github.com/emskye96/chameleon-ng) which is a much cleaner and more featureful version of this project.

**Comment by notradger** [comment]
Nice man.. Thanks for the heads up.. You made my day :+1:
